### ISSUE TITLE
Consider switching to a CC license

### ISSUE THREAD

**Issue by mekkim** [dewan-ahmed/recruiter-response-template#1]
Creative Commons are specifically tailored for written works (as opposed to other open source licenses that deal more with source code).  CC-BY (Attribution 4.0 international) is the most comparable to the Apache license currently listed.  More details: [https://creativecommons.org/choose/](https://creativecommons.org/choose/)

**Comment by dewan-ahmed** [comment]
Thanks @mekkim for the suggestion. CC0 is the only option I see in the template. Please let me know if this looks ok: https://github.com/dewan-ahmed/recruiter-response-template/pull/3

**Comment by dewan-ahmed** [comment]
Fixed via https://github.com/dewan-ahmed/recruiter-response-template/pull/3.
